[package]
  cjc-version = "1.0.4"
  name = "raylib"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = "src"
  output-type = "executable"
  compile-option = "-Llib/ -lraylib"
  override-compile-option = ""
  link-option = ""
  [package.package-configuration]

[dependencies]
